sudo: required
services:
  - docker

before_install:
  - docker build -t prasunmax/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true prasunmax/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-401275114950"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access:key: $AWS_SECRET_KEY